### PR TITLE
Add Documentation Notes

### PR DESCRIPTION
**Pull request by crow1170**

### CODE REVIEW

**Comment by hgarrereyn** [comment]
Sorry I've been busy with school recently, at first glance this looks good. I'll review sometime this week.

**Comment by crow1170** [comment]
Still planning on adding this, @hgarrereyn?

**Comment by hgarrereyn** [comment]
totally forgot about this, my bad

**Comment by crow1170** [comment]
Thanks for merging this. It probably doesn't affect much in the long run but it means a lot to me personally.

**Pull request merged**
